### ISSUE TITLE
Clearer information on Supported Software Versions

### ISSUE THREAD

**Issue by thewishy** [f5devcentral/f5-journeys-lab-ucs-modifier#3]
We've been working with a customer with an exceptionally old release of BIG-IP (10.2.4)

It seems 10.2.4 doesn't work as .ucs_platform files don't exist

`Traceback (most recent call last):
  File "/usr/local/bin/ucs-modifier", line 33, in <module>
    sys.exit(load_entry_point('ucs-modifier', 'console_scripts', 'ucs-modifier')())
  File "/modifier/ucs_modifier/calypso_ucs_modifier.py", line 58, in main
    reader = UcsReader(output_dir)
  File "/modifier/ucs_modifier/modifier/reader.py", line 20, in __init__
    self.ucs_platform_kwargs = self._get_ucs_platform_kwargs()
  File "/modifier/ucs_modifier/modifier/reader.py", line 52, in _get_ucs_platform_kwargs
    with open(ucs_version_fn) as ucs_file:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpfzfu9ua2/config/.ucs_platform'`

This doesn't necessarily need to be fixed, but some clear information about supported releases would be useful. If you'd like to fix it, pop me a message and I'll get the UCS files

**Comment by mnaumiuk** [comment]
Thanks for the suggestion, info was added to the description with v1.0.1
